export const env = {
DATABASE_URL: process.env.DATABASE_URL!,
APP_URL: process.env.APP_URL!,
EMAIL_FROM: process.env.EMAIL_FROM!,
RESEND_API_KEY: process.env.RESEND_API_KEY!,
STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY!,
STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY!,
STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET!,
SESSION_SECRET: process.env.SESSION_SECRET!,
RATE_LIMIT_WINDOW_MS: Number(process.env.RATE_LIMIT_WINDOW_MS || 60000),
RATE_LIMIT_MAX: Number(process.env.RATE_LIMIT_MAX || 60)
};